# Generated by Django 5.1.5 on 2025-03-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0007_diaryvideo_remove_memoryvideo_user_delete_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
